### PR TITLE
Auto-layout when creating nodes

### PR DESCRIPTION
**Pull request by s9ferech**
### Pull Request Description

This PR implements the auto-layout described in issue #1550.

New nodes are pushed to the right into the first gap that is large enough:

If there isn't enough spacing then it will be pushed further:

The "interface" debug scene was updated to contain a "foo", "bar" and "baz" node that demonstrate the new auto-layout:

### Checklist
Please include the following checklist in your PR:

- [x] The `CHANGELOG.md` was updated with the changes introduced in this PR.
- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guide.
- [ ] All code has automatic tests where possible.
- [ ] All code has been profiled where possible.
- [x] All code has been manually tested in the IDE.
- [x] All code has been manually tested in the "debug/interface" scene.
- [ ] All code has been manually tested by the PR owner against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).
- [ ] All code has been manually tested by at least one reviewer against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).

### CODE REVIEW

File: src/rust/ide/view/src/project.rs [hunk 1]
```diff
@@ -236,6 +230,48 @@ impl Model {
...
+                }
+            }
+        }
+        let pos = Vector2(x,y);
+        self.graph_editor.add_node.emit(());
+        let node_id = self.graph_editor.frp.output.node_added.value();
+        self.graph_editor.set_node_position((node_id,pos));
+        node_id
+    }
+
```
Comment (wdanilo) [inline src/rust/ide/view/src/project.rs]: Why this is not a function of graph editor? Graph editor is responsible for creating new nodes, it should be its responsibility to find the place as well IMO

File: src/rust/ide/view/src/project.rs [hunk 2]
```diff
@@ -325,8 +361,8 @@ mod js {
 #[allow(missing_docs)]
 #[derive(Clone,CloneRef,Debug)]
 pub struct View {
-    model   : Model,
-    pub frp : Frp,
+    pub model : Model,
```
Comment (wdanilo) [inline src/rust/ide/view/src/project.rs]: making model pub is rather a bad practice. We should rather not do it. Why is it needed?

File: src/rust/ide/view/src/project.rs [hunk 3]
```diff
@@ -236,6 +230,48 @@ impl Model {
         node_id
     }
 
+    /// Ads a new node below `parent` and returns its ID. If there is not enough space right below
+    /// `parent` then the new node is moved to the right to first gap that is large enough.
+    pub fn add_node_below(&self, parent:NodeId) -> NodeId {
+        let parent_pos = self.graph_editor.model.get_node_position(parent).unwrap_or_default();
+        let styles     = StyleWatch::new(&self.app.display.scene().style_sheet);
+        use ensogl_theme::project as theme;
```
Comment (wdanilo) [inline src/rust/ide/view/src/project.rs]: This line inbetween var defs looks strange

File: src/rust/ide/view/src/project.rs [hunk 4]
```diff
@@ -236,6 +230,48 @@ impl Model {
...
+        let x_gap    = styles.get_number(theme::default_x_gap_between_nodes);
+        let y_gap    = styles.get_number(theme::default_y_gap_between_nodes);
+        let y_offset = y_gap + node::HEIGHT;
+        let mut x    = parent_pos.x;
+        let y        = parent_pos.y - y_offset;
+        // Push x to the right until we find a position where we have enough space for the new
+        // node, including a margin of size `x_gap`/`y_gap` on all sides.
+        {
+            let nodes             = self.graph_editor.model.nodes.all.raw.borrow();
+            // We subtract `f32::EPSILON` to be sure that we do not include the selected node.
```
Comment (wdanilo) [inline src/rust/ide/view/src/project.rs]: I do not understand neither this comment nor this line of code. What would happen if we do not subtract it? Please describe it more clear in the docs :)

File: src/rust/ide/view/src/project.rs [hunk 5]
```diff
@@ -236,6 +230,48 @@ impl Model {
...
+            let maybe_overlapping = nodes.values().filter(|node|
+                (node.position().y - y).abs() < y_offset - f32::EPSILON);
+            let maybe_overlapping = maybe_overlapping.sorted_by_key(|n|
+                OrderedFloat(n.position().x));
+            // This is how much horizontal space we are looking for.
+            let assumed_width = styles.get_number(theme::assumed_node_width);
```
Comment (wdanilo) [inline src/rust/ide/view/src/project.rs]: I think that `theme:: assumed_node_width` is confusing. The name should be more explicit, like "minimal_x_spacing_for_a_new_node" or something like that

File: src/rust/ide/view/src/project.rs [hunk 6]
```diff
@@ -236,6 +230,48 @@ impl Model {
...
+                let node_right = node.position().x + node.view.model.width() + x_gap;
+                if x + assumed_width > node_left {
+                    x = x.max(node_right);
+                } else {
+                    // Since `maybe_overlapping` is sorted, we know that the if-condition will
+                    // be false for all following `node`s as well. Therefore, we can skip the
+                    // remaining iterations.
+                    break;
+                }
+            }
```
Comment (wdanilo) [inline src/rust/ide/view/src/project.rs]: can we rework the loop to use e.g. while loop and not use `break`? We try to avoid `break` always when possible to make the function/block exit in one place.

File: CHANGELOG.md [hunk 7]
```diff
@@ -11,6 +11,10 @@ these updates be shipped in a stable release before the end of the year.
 - [New look of open project dialog.][1700]. Now it has "Open project" title on
   the top.
 - [Documentation cooments are displayed next to the nodes.][1744].
+- [Auto-layout for new nodes.][1755]. When a node is selected and a new node
+  gets created below using <kbd>Tab</kbd> then the new node is automatically
+  positioned far enough to the right to find sufficient space and avoid
+  overlapping with existing nodes.
```
Comment (wdanilo) [inline CHANGELOG.md]: Ask Ara for help in rewording that to something sounding slightly nicer, please :)

File: src/rust/ide/view/src/project.rs (hunk 1 above)
Comment (s9ferech) [reply src/rust/ide/view/src/project.rs]: I just left it here because the position was also computed here before (It was much simpler at that time). I suppose it could easily be defined as a method on `GraphEditor`. I will try that out.

File: src/rust/ide/view/src/project.rs (hunk 2 above)
Comment (s9ferech) [reply src/rust/ide/view/src/project.rs]: `add_node_below` needs to be defined as a method on `Model`, such that we can easily use it from the FRP network. But we also need the method to demonstrate the auto-layout in the demo scene. The model needs to be public for that.

File: src/rust/ide/view/src/project.rs (hunk 4 above)
Comment (s9ferech) [reply src/rust/ide/view/src/project.rs]: What could happen is that rounding errors lead us to consider the parent root as overlapping, because lies exactly on the threshold where we should not count it.

File: CHANGELOG.md (hunk 7 above)
Comment (s9ferech) [reply CHANGELOG.md]: @iamrecursion, would you help here, please?

File: src/rust/ide/view/src/project.rs (hunk 6 above)
Comment (s9ferech) [reply src/rust/ide/view/src/project.rs]: Then I would prefer to just remove the `break` if that is fine. It has a minimal performance impact, but keeps the code more readable.

File: src/rust/ide/view/src/project.rs (hunk 1 above)
Comment (s9ferech) [reply src/rust/ide/view/src/project.rs]: I just noticed that `default_y_gap_between_nodes` is defined in the `project` part of the theme as well. Should that also be moved to the graph-editor part then?

Comment (wdanilo) [reply src/rust/ide/view/src/project.rs]: yes, it seems so

File: src/rust/ide/view/src/project.rs (hunk 6 above)
Comment (wdanilo) [reply src/rust/ide/view/src/project.rs]: nah, keeping performance optimal is alwasy better. So its better to keep it, but its even more nicer to use while

Comment (s9ferech) [reply src/rust/ide/view/src/project.rs]: Unless you have a concrete suggestion to implement it with a while loop, I will leave it like this, because I don't see how I could do it better.

File: src/rust/ide/view/graph-editor/src/lib.rs [hunk 8]
```diff
@@ -2039,6 +2042,50 @@ impl GraphEditor {
         self.frp.add_node.emit(());
         self.frp.output.node_added.value()
     }
+
+    /// Ads a new node below `parent` and returns its ID. If there is not enough space right below
+    /// `parent` then the new node is moved to the right to first gap that is large enough.
+    pub fn add_node_below(&self, parent:NodeId) -> NodeId {
```
Comment (farmaazon) [inline src/rust/ide/view/graph-editor/src/lib.rs]: I would rename `parent` to something else, maybe `above`? Because parent in this place may suggest rather some display objects hierarchy.

File: src/rust/ide/view/graph-editor/src/lib.rs [hunk 9]
```diff
@@ -2039,6 +2042,50 @@ impl GraphEditor {
...
+        use ensogl_theme::graph_editor as theme;
+        let parent_pos = self.model.get_node_position(parent).unwrap_or_default();
+        let styles     = StyleWatch::new(&self.model.app.display.scene().style_sheet);
```
Comment (wdanilo) [inline src/rust/ide/view/graph-editor/src/lib.rs]: This is slow. Style watch should be created once and remembered instead.

File: src/rust/ide/view/graph-editor/src/lib.rs [hunk 10]
```diff
@@ -2039,6 +2042,50 @@ impl GraphEditor {
...
+        let x_gap      = styles.get_number(theme::default_x_gap_between_nodes);
+        let y_gap      = styles.get_number(theme::default_y_gap_between_nodes);
```
Comment (wdanilo) [inline src/rust/ide/view/graph-editor/src/lib.rs]: This is slow as well - this should be read in FRP by using StyleWatchFRP instead. Now, we are using a lot of string queries in hashmaps everytime we create a new node. When using FRP, this will be done only when theme changes.

File: src/rust/ide/view/graph-editor/src/lib.rs [hunk 11]
```diff
@@ -2039,6 +2042,50 @@ impl GraphEditor {
...
+                (node.position().y - y).abs() < y_offset - f32::EPSILON);
+            let maybe_overlapping = maybe_overlapping.sorted_by_key(|n|
+                OrderedFloat(n.position().x));
+            // This is how much horizontal space we are looking for.
+            let min_spacing = styles.get_number(theme::minimal_x_spacing_for_new_nodes);
+            for node in maybe_overlapping {
+                let node_left  = node.position().x - x_gap;
+                let node_right = node.position().x + node.view.model.width() + x_gap;
+                if x + min_spacing > node_left {
+                    x = x.max(node_right);
```
Comment (wdanilo) [inline src/rust/ide/view/graph-editor/src/lib.rs]: amazing job with the comments!!! ❤️

**Review by wdanilo — COMMENTED** [review]
We are almost there! Let's fix these small perf things, and lets merge it :)

**Review by farmaazon — APPROVED** [review]
I'm ok with the code if you apply the @wdanilo comments.

**Comment by MichaelMauderer** [comment]
@s9ferech What is the status of this?

**Comment by s9ferech** [comment]
> @s9ferech What is the status of this?

Waiting for re-review by Wojciech.

**Review by MichaelMauderer — APPROVED** [review]
